using Serilog.Core;
using Serilog.Events;

namespace DnnMigration.Api.Logging;

/// <summary>
/// Removes the log properties that the hosting layer attaches from caller input, so that no
/// entry the application writes carries a value the caller chose.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why this exists at all.</b> The properties an application writes are the ones it chose,
/// and every message template in this solution is authored to carry nothing personal. The
/// hosting layer, however, opens a logging scope for the duration of each request, and Serilog's
/// logging adapter promotes the members of that scope onto <em>every</em> event written while the
/// request is being handled. One of those members is the raw request path. The consequence is
/// that removing the path from a message template achieves nothing on its own: the same value
/// arrives on the same entry from the scope, under the name the hosting layer gave it, and it
/// arrives on the audit events and the database entries too - not only on the request envelope.
/// </para>
/// <para>
/// <b>Why the path in particular.</b> A path is caller input. The identifiers in it are
/// frequently personal - an email address used as a route key, an account number - and a path is
/// also where a credential lands when a caller types one into the wrong field, where it is then
/// copied into the highest-volume, longest-retained and most widely-readable log the application
/// produces. The route TEMPLATE is recorded in its place by <c>RequestLoggingMiddleware</c>: it
/// is authored text, it says which operation was reached, and unlike a path it groups every
/// request to that operation under one value.
/// </para>
/// <para>
/// <b>Why it is an enricher and not a configuration switch.</b> There is no switch. The scope is
/// created by the hosting layer before any middleware runs and cannot be opted out of, and the
/// scope's properties are attached to an event <em>before</em> the pipeline's own enrichers run -
/// which is why declaring a replacement value has no effect, since a property is only ever added
/// when absent. An enricher registered on the pipeline is therefore the one position from which
/// an already-attached property can be removed.
/// </para>
/// <para>
/// <b>Nothing diagnostic is lost.</b> The request identifier the hosting scope also carries is
/// server-generated and is left in place, the correlation identifier is on every entry and on
/// every response, and the request envelope names the route template, the method, the status and
/// the duration. What is removed is the one member of that set that the caller wrote.
/// </para>
/// <para>
/// MIGRATION: net-new, with no legacy counterpart - the legacy application wrote no request log
/// at all. It is recorded here because the divergence is not from legacy behaviour but from the
/// framework's default behaviour, which is to publish the path everywhere.
/// </para>
/// </remarks>
internal sealed class SensitiveLogPropertyScrubber : ILogEventEnricher
{
    /// <summary>
    /// Names of the properties removed from every event.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A closed list, deliberately short, and deliberately naming properties this application
    /// never sets itself: everything here is attached by a layer below and is removed precisely
    /// because it was not authored here.
    /// </para>
    /// <para>
    /// <c>RequestPath</c> is the hosting scope's copy of the raw request path. Its sibling
    /// <c>RequestId</c> is NOT removed, because it is generated by the server, identifies the
    /// request for an operator, and cannot carry anything the caller wrote.
    /// </para>
    /// </remarks>
    private static readonly string[] ScrubbedProperties = ["RequestPath"];

    /// <summary>Removes every scrubbed property from the event.</summary>
    /// <param name="logEvent">The event being enriched.</param>
    /// <param name="propertyFactory">
    /// Creates property values. Unused: this enricher only ever takes properties away.
    /// </param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="logEvent"/> is <see langword="null"/>.
    /// </exception>
    /// <remarks>
    /// Removal is unconditional and silent when the property is absent, so the same enricher is
    /// correct for an event written outside a request - a startup entry, or a background one -
    /// where the hosting scope was never opened.
    /// </remarks>
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        ArgumentNullException.ThrowIfNull(logEvent);

        foreach (string property in ScrubbedProperties)
        {
            logEvent.RemovePropertyIfPresent(property);
        }
    }
}
