// <auto-generated />
using System;
using DnnMigration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnnMigration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DnnDbContext))]
    [Migration("20260730120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DnnMigration.Domain.Entities.DesktopModule", b =>
                {
                    b.Property<int>("DesktopModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DesktopModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesktopModuleId"));

                    b.Property<string>("BusinessControllerClass")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BusinessControllerClass");

                    b.Property<string>("CompatibleVersions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CompatibleVersions");

                    b.Property<string>("Dependencies")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("Dependencies");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Description");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("FolderName");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("FriendlyName");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit")
                        .HasColumnName("IsPremium");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ModuleName");

                    b.Property<string>("Permissions")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("Permissions");

                    b.Property<int>("SupportedFeatures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SupportedFeatures");

                    b.Property<string>("Version")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Version");

                    b.HasKey("DesktopModuleId")
                        .HasName("PK_DesktopModules");

                    b.HasIndex("FriendlyName")
                        .HasDatabaseName("IX_DesktopModules_FriendlyName");

                    b.HasIndex("ModuleName")
                        .IsUnique()
                        .HasDatabaseName("IX_DesktopModules_ModuleName");

                    b.ToTable("DesktopModules", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"), 0L);

                    b.Property<bool>("AllTabs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("AllTabs");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("EndDate");

                    b.Property<string>("Footer")
                        .HasColumnType("ntext")
                        .HasColumnName("Footer");

                    b.Property<string>("Header")
                        .HasColumnType("ntext")
                        .HasColumnName("Header");

                    b.Property<bool?>("InheritViewPermissions")
                        .HasColumnType("bit")
                        .HasColumnName("InheritViewPermissions");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("ModuleDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    b.Property<string>("ModuleTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ModuleTitle");

                    b.Property<int?>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("StartDate");

                    b.HasKey("ModuleId")
                        .HasName("PK_Modules");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ModuleId"), false);

                    b.HasIndex("ModuleDefinitionId")
                        .HasDatabaseName("IX_Modules");

                    b.ToTable("Modules", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleControl", b =>
                {
                    b.Property<int>("ModuleControlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleControlID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleControlId"));

                    b.Property<string>("ControlKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ControlKey");

                    b.Property<string>("ControlSrc")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ControlSrc");

                    b.Property<string>("ControlTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ControlTitle");

                    b.Property<int>("ControlType")
                        .HasColumnType("int")
                        .HasColumnName("ControlType");

                    b.Property<string>("HelpUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HelpUrl");

                    b.Property<string>("IconFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IconFile");

                    b.Property<int?>("ModuleDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    b.Property<bool>("SupportsPartialRendering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("SupportsPartialRendering");

                    b.Property<int?>("ViewOrder")
                        .HasColumnType("int")
                        .HasColumnName("ViewOrder");

                    b.HasKey("ModuleControlId")
                        .HasName("PK_ModuleControls");

                    b.HasIndex("ModuleDefinitionId", "ControlKey", "ControlSrc")
                        .IsUnique()
                        .HasDatabaseName("IX_ModuleControls");

                    b.ToTable("ModuleControls", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleDefinition", b =>
                {
                    b.Property<int>("ModuleDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleDefinitionId"));

                    b.Property<int>("DefaultCacheTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("DefaultCacheTime");

                    b.Property<int>("DesktopModuleId")
                        .HasColumnType("int")
                        .HasColumnName("DesktopModuleID");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("FriendlyName");

                    b.HasKey("ModuleDefinitionId")
                        .HasName("PK_ModuleDefinitions");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ModuleDefinitionId"), false);

                    b.HasIndex("DesktopModuleId")
                        .HasDatabaseName("IX_ModuleDefinitions_1");

                    b.HasIndex("FriendlyName")
                        .IsUnique()
                        .HasDatabaseName("IX_ModuleDefinitions");

                    b.ToTable("ModuleDefinitions", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModulePermission", b =>
                {
                    b.Property<int>("ModulePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModulePermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModulePermissionId"));

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("bit")
                        .HasColumnName("AllowAccess");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ModulePermissionId")
                        .HasName("PK_ModulePermission");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_ModulePermission_Modules");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_ModulePermission_Permission");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_ModulePermission_Roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ModulePermission_Users");

                    b.HasIndex("ModuleId", "PermissionId", "RoleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ModulePermission");

                    b.ToTable("ModulePermission", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleSetting", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<string>("SettingName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SettingName");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("SettingValue");

                    b.HasKey("ModuleId", "SettingName")
                        .HasName("PK_ModuleSettings");

                    b.ToTable("ModuleSettings", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<int>("ModuleDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PermissionCode");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PermissionKey");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PermissionName");

                    b.HasKey("PermissionId")
                        .HasName("PK_Permission");

                    b.HasIndex("PermissionCode", "ModuleDefinitionId", "PermissionKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission");

                    b.ToTable("Permission", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Portal", b =>
                {
                    b.Property<int>("PortalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalId"), -1L);

                    b.Property<int?>("AdminTabId")
                        .HasColumnType("int")
                        .HasColumnName("AdminTabId");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int")
                        .HasColumnName("AdministratorId");

                    b.Property<int?>("AdministratorRoleId")
                        .HasColumnType("int")
                        .HasColumnName("AdministratorRoleId");

                    b.Property<string>("BackgroundFile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BackgroundFile");

                    b.Property<int>("BannerAdvertising")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("BannerAdvertising");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en-US")
                        .HasColumnName("DefaultLanguage");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ExpiryDate");

                    b.Property<string>("FooterText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FooterText");

                    b.Property<string>("HomeDirectory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("HomeDirectory");

                    b.Property<int?>("HomeTabId")
                        .HasColumnType("int")
                        .HasColumnName("HomeTabId");

                    b.Property<decimal>("HostFee")
                        .HasColumnType("money")
                        .HasDefaultValue(0m)
                        .HasColumnName("HostFee");

                    b.Property<int>("HostSpace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("HostSpace");

                    b.Property<string>("KeyWords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("KeyWords");

                    b.Property<int?>("LoginTabId")
                        .HasColumnType("int")
                        .HasColumnName("LoginTabId");

                    b.Property<string>("LogoFile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogoFile");

                    b.Property<int>("PageQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PageQuota");

                    b.Property<string>("PaymentProcessor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PaymentProcessor");

                    b.Property<Guid>("PortalGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("PortalName");

                    b.Property<string>("ProcessorPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProcessorPassword");

                    b.Property<string>("ProcessorUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProcessorUserId");

                    b.Property<int?>("RegisteredRoleId")
                        .HasColumnType("int")
                        .HasColumnName("RegisteredRoleId");

                    b.Property<int?>("SiteLogHistory")
                        .HasColumnType("int")
                        .HasColumnName("SiteLogHistory");

                    b.Property<int?>("SplashTabId")
                        .HasColumnType("int")
                        .HasColumnName("SplashTabId");

                    b.Property<int>("TimeZoneOffset")
                        .HasColumnType("int")
                        .HasDefaultValue(-8)
                        .HasColumnName("TimezoneOffset");

                    b.Property<int>("UserQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("UserQuota");

                    b.Property<int>("UserRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("UserRegistration");

                    b.Property<int?>("UserTabId")
                        .HasColumnType("int")
                        .HasColumnName("UserTabId");

                    b.HasKey("PortalId")
                        .HasName("PK_Portals");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("PortalId"), false);

                    b.ToTable("Portals", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.PortalAlias", b =>
                {
                    b.Property<int>("PortalAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortalAliasID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalAliasId"));

                    b.Property<string>("HttpAlias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HTTPAlias");

                    b.Property<int>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.HasKey("PortalAliasId")
                        .HasName("PK_PortalAlias");

                    b.HasIndex("HttpAlias")
                        .IsUnique()
                        .HasDatabaseName("IX_PortalAlias");

                    b.ToTable("PortalAlias", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.PortalDesktopModule", b =>
                {
                    b.Property<int>("PortalDesktopModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortalDesktopModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalDesktopModuleId"));

                    b.Property<int>("DesktopModuleId")
                        .HasColumnType("int")
                        .HasColumnName("DesktopModuleID");

                    b.Property<int>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.HasKey("PortalDesktopModuleId")
                        .HasName("PK_PortalDesktopModules");

                    b.HasIndex("PortalId", "DesktopModuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_PortalDesktopModules");

                    b.ToTable("PortalDesktopModules", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ProfilePropertyDefinition", b =>
                {
                    b.Property<int>("PropertyDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PropertyDefinitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyDefinitionId"));

                    b.Property<int>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("DataType");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("ntext")
                        .HasColumnName("DefaultValue");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("Required");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("Visible");

                    b.Property<int>("Length")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Length");

                    b.Property<int?>("ModuleDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleDefID");

                    b.Property<int?>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<string>("PropertyCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PropertyCategory");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PropertyName");

                    b.Property<string>("ValidationExpression")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ValidationExpression");

                    b.Property<int>("ViewOrder")
                        .HasColumnType("int")
                        .HasColumnName("ViewOrder");

                    b.HasKey("PropertyDefinitionId")
                        .HasName("PK_ProfilePropertyDefinition");

                    b.HasIndex("PropertyName")
                        .HasDatabaseName("IX_ProfilePropertyDefinition_PropertyName");

                    b.HasIndex("PortalId", "ModuleDefinitionId", "PropertyName")
                        .IsUnique()
                        .HasDatabaseName("IX_ProfilePropertyDefinition");

                    b.ToTable("ProfilePropertyDefinition", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 0L);

                    b.Property<bool>("AutoAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("AutoAssignment");

                    b.Property<string>("BillingFrequency")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("BillingFrequency");

                    b.Property<int?>("BillingPeriod")
                        .HasColumnType("int")
                        .HasColumnName("BillingPeriod");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("IconFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IconFile");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsPublic");

                    b.Property<int?>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<int?>("RoleGroupId")
                        .HasColumnType("int")
                        .HasColumnName("RoleGroupID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoleName");

                    b.Property<string>("RsvpCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RSVPCode");

                    b.Property<decimal?>("ServiceFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m)
                        .HasColumnName("ServiceFee");

                    b.Property<decimal?>("TrialFee")
                        .HasColumnType("money")
                        .HasColumnName("TrialFee");

                    b.Property<string>("TrialFrequency")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("TrialFrequency");

                    b.Property<int?>("TrialPeriod")
                        .HasColumnType("int")
                        .HasColumnName("TrialPeriod");

                    b.HasKey("RoleId")
                        .HasName("PK_Roles");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("RoleId"), false);

                    b.HasIndex("BillingFrequency")
                        .HasDatabaseName("IX_Roles");

                    b.HasIndex("PortalId", "RoleName")
                        .IsUnique()
                        .HasDatabaseName("IX_RoleName");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.RoleGroup", b =>
                {
                    b.Property<int>("RoleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleGroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleGroupId"), 0L);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<int>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<string>("RoleGroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoleGroupName");

                    b.HasKey("RoleGroupId")
                        .HasName("PK_RoleGroups");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("RoleGroupId"), false);

                    b.HasIndex("PortalId", "RoleGroupName")
                        .IsUnique()
                        .HasDatabaseName("IX_RoleGroupName");

                    b.ToTable("RoleGroups", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Tab", b =>
                {
                    b.Property<int>("TabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabId"), 0L);

                    b.Property<string>("ContainerSrc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ContainerSrc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("DisableLink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DisableLink");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("EndDate");

                    b.Property<string>("IconFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IconFile");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsSecure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSecure");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsVisible");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("KeyWords");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Level");

                    b.Property<string>("PageHeadText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PageHeadText");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<int?>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<int?>("RefreshInterval")
                        .HasColumnType("int")
                        .HasColumnName("RefreshInterval");

                    b.Property<string>("SkinSrc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SkinSrc");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("StartDate");

                    b.Property<string>("TabName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TabName");

                    b.Property<int>("TabOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TabOrder");

                    b.Property<string>("TabPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TabPath");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Url");

                    b.HasKey("TabId")
                        .HasName("PK_Tabs");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("TabId"), false);

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Tabs_2");

                    b.HasIndex("PortalId")
                        .HasDatabaseName("IX_Tabs_1");

                    b.ToTable("Tabs", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabModule", b =>
                {
                    b.Property<int>("TabModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TabModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabModuleId"));

                    b.Property<string>("Alignment")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Alignment");

                    b.Property<string>("Border")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Border");

                    b.Property<int>("CacheTime")
                        .HasColumnType("int")
                        .HasColumnName("CacheTime");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Color");

                    b.Property<string>("ContainerSrc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ContainerSrc");

                    b.Property<bool>("DisplayPrint")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("DisplayPrint");

                    b.Property<bool>("DisplaySyndicate")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("DisplaySyndicate");

                    b.Property<bool>("DisplayTitle")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("DisplayTitle");

                    b.Property<string>("IconFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IconFile");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("ModuleOrder")
                        .HasColumnType("int")
                        .HasColumnName("ModuleOrder");

                    b.Property<string>("PaneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PaneName");

                    b.Property<int>("TabId")
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    b.Property<int>("Visibility")
                        .HasColumnType("int")
                        .HasColumnName("Visibility");

                    b.HasKey("TabModuleId")
                        .HasName("PK_TabModules");

                    b.HasIndex("TabId", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_TabModules");

                    b.ToTable("TabModules", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabModuleSetting", b =>
                {
                    b.Property<int>("TabModuleId")
                        .HasColumnType("int")
                        .HasColumnName("TabModuleID");

                    b.Property<string>("SettingName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SettingName");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("SettingValue");

                    b.HasKey("TabModuleId", "SettingName")
                        .HasName("PK_TabModuleSettings");

                    b.ToTable("TabModuleSettings", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabPermission", b =>
                {
                    b.Property<int>("TabPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TabPermissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabPermissionId"));

                    b.Property<bool>("AllowAccess")
                        .HasColumnType("bit")
                        .HasColumnName("AllowAccess");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionID");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("TabId")
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TabPermissionId")
                        .HasName("PK_TabPermission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_TabPermission_Permission");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_TabPermission_Roles");

                    b.HasIndex("TabId")
                        .HasDatabaseName("IX_TabPermission_Tabs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TabPermission_Users");

                    b.HasIndex("TabId", "PermissionId", "RoleId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TabPermission");

                    b.ToTable("TabPermission", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AffiliateId")
                        .HasColumnType("int")
                        .HasColumnName("AffiliateId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsSuperUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSuperUser");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<bool>("UpdatePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("UpdatePassword");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Username");

                    b.HasKey("UserId")
                        .HasName("PK_Users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserPortal", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsAuthorised")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Authorised");

                    b.Property<int>("UserPortalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserPortalId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPortalId"));

                    b.HasKey("UserId", "PortalId")
                        .HasName("PK_UserPortals");

                    b.HasIndex("PortalId")
                        .HasDatabaseName("IX_UserPortals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserPortals_1");

                    b.ToTable("UserPortals", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserProfileValue", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyDefinitionID");

                    b.Property<string>("PropertyText")
                        .HasColumnType("ntext")
                        .HasColumnName("PropertyText");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(3750)
                        .HasColumnType("nvarchar(3750)")
                        .HasColumnName("PropertyValue");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Visibility");

                    b.HasKey("ProfileId")
                        .HasName("PK_UserProfile");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ProfileId"), false);

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserProfile");

                    b.ToTable("UserProfile", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime")
                        .HasColumnName("EffectiveDate");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ExpiryDate");

                    b.Property<bool?>("IsTrialUsed")
                        .HasColumnType("bit")
                        .HasColumnName("IsTrialUsed");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserRoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_1");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Module", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("Modules")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Modules_ModuleDefinitions");

                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany("Modules")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Modules_Portals");

                    b.Navigation("ModuleDefinition");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleControl", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("ModuleControls")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ModuleControls_ModuleDefinitions");

                    b.Navigation("ModuleDefinition");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleDefinition", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.DesktopModule", "DesktopModule")
                        .WithMany("ModuleDefinitions")
                        .HasForeignKey("DesktopModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ModuleDefinitions_DesktopModules");

                    b.Navigation("DesktopModule");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModulePermission", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Module", "Module")
                        .WithMany("ModulePermissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ModulePermission_Modules");

                    b.HasOne("DnnMigration.Domain.Entities.Permission", "Permission")
                        .WithMany("ModulePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ModulePermission_Permission");

                    b.HasOne("DnnMigration.Domain.Entities.Role", "Role")
                        .WithMany("ModulePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DnnMigration.Domain.Entities.User", "User")
                        .WithMany("ModulePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ModulePermissionUsers");

                    b.Navigation("Module");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleSetting", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Module", "Module")
                        .WithMany("Settings")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ModuleSettings_Modules");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.PortalAlias", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany("PortalAliases")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortalAlias_Portals");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.PortalDesktopModule", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.DesktopModule", "DesktopModule")
                        .WithMany("PortalDesktopModules")
                        .HasForeignKey("DesktopModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortalDesktopModules_DesktopModules");

                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany("PortalDesktopModules")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PortalDesktopModules_Portals");

                    b.Navigation("DesktopModule");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ProfilePropertyDefinition", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("ProfilePropertyDefinitions")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany()
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ProfilePropertyDefinition_Portals");

                    b.Navigation("ModuleDefinition");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Role", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany("Roles")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Roles_Portals");

                    b.HasOne("DnnMigration.Domain.Entities.RoleGroup", "RoleGroup")
                        .WithMany("Roles")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Roles_RoleGroups");

                    b.Navigation("Portal");

                    b.Navigation("RoleGroup");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.RoleGroup", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany()
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleGroups_Portals");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Tab", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Tab", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tabs_Tabs");

                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany("Tabs")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Tabs_Portals");

                    b.Navigation("Parent");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabModule", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Module", "Module")
                        .WithMany("TabModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabModules_Modules");

                    b.HasOne("DnnMigration.Domain.Entities.Tab", "Tab")
                        .WithMany("TabModules")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabModules_Tabs");

                    b.Navigation("Module");

                    b.Navigation("Tab");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabModuleSetting", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.TabModule", "TabModule")
                        .WithMany("Settings")
                        .HasForeignKey("TabModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabModuleSettings_TabModules");

                    b.Navigation("TabModule");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabPermission", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Permission", "Permission")
                        .WithMany("TabPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabPermission_Permission");

                    b.HasOne("DnnMigration.Domain.Entities.Role", "Role")
                        .WithMany("TabPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DnnMigration.Domain.Entities.Tab", "Tab")
                        .WithMany("TabPermissions")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TabPermission_Tabs");

                    b.HasOne("DnnMigration.Domain.Entities.User", "User")
                        .WithMany("TabPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TabPermission_Users");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("Tab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserPortal", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Portal", "Portal")
                        .WithMany("UserPortals")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPortals_Portals");

                    b.HasOne("DnnMigration.Domain.Entities.User", "User")
                        .WithMany("UserPortals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPortals_Users");

                    b.Navigation("Portal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserProfileValue", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.ProfilePropertyDefinition", "PropertyDefinition")
                        .WithMany("ProfileValues")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfile_ProfilePropertyDefinition");

                    b.HasOne("DnnMigration.Domain.Entities.User", "User")
                        .WithMany("UserProfileValues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfile_Users");

                    b.Navigation("PropertyDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("DnnMigration.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("DnnMigration.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.DesktopModule", b =>
                {
                    b.Navigation("ModuleDefinitions");

                    b.Navigation("PortalDesktopModules");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Module", b =>
                {
                    b.Navigation("ModulePermissions");

                    b.Navigation("Settings");

                    b.Navigation("TabModules");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ModuleDefinition", b =>
                {
                    b.Navigation("ModuleControls");

                    b.Navigation("Modules");

                    b.Navigation("ProfilePropertyDefinitions");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Permission", b =>
                {
                    b.Navigation("ModulePermissions");

                    b.Navigation("TabPermissions");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Portal", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("PortalAliases");

                    b.Navigation("PortalDesktopModules");

                    b.Navigation("Roles");

                    b.Navigation("Tabs");

                    b.Navigation("UserPortals");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.ProfilePropertyDefinition", b =>
                {
                    b.Navigation("ProfileValues");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Role", b =>
                {
                    b.Navigation("ModulePermissions");

                    b.Navigation("TabPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.RoleGroup", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.Tab", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TabModules");

                    b.Navigation("TabPermissions");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.TabModule", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("DnnMigration.Domain.Entities.User", b =>
                {
                    b.Navigation("ModulePermissions");

                    b.Navigation("TabPermissions");

                    b.Navigation("UserPortals");

                    b.Navigation("UserProfileValues");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
