<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.12.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DnnMigration.Domain\DnnMigration.Domain.csproj" />
  </ItemGroup>

</Project>
