namespace DnnMigration.Application.Validation;

/// <summary>
/// The closed sets of field names a caller may name in <c>PagedRequest.SortBy</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Closed by default.</b> A name that appears in no set below is rejected at the
/// boundary. The point of an allowlist rather than a pattern is that no caller-supplied
/// text ever reaches an <c>ORDER BY</c> clause: what reaches the repository is a member
/// of a set fixed at compile time, so the ordering clause is composed from constants
/// this assembly owns rather than from anything that arrived on the wire. A pattern
/// rule - "letters and digits only", say - would still hand the repository a string it
/// had to trust, and would have to be tightened again every time someone widened it.
/// </para>
/// <para>
/// <b>Two levels, because one shared contract serves every collection.</b>
/// <see cref="All"/> is the union, and it is the bound that <c>PagedRequestValidator</c>
/// applies: that validator cannot know which collection a given request addresses,
/// because <c>PagedRequest</c> is one shared contract bound by every collection endpoint
/// and FluentValidation resolves one validator per request type. Applying the union there
/// is what makes an unrecognised name a 400 before any service runs. The per-collection
/// sets are the narrower authority for a listing that knows which collection it is
/// reading, and they are declared here, beside the union that is built from them, so the
/// two can never drift apart. They are <see langword="internal"/> because the listings
/// that consult them are application services in this same assembly; nothing outside it
/// needs, or is given, the ability to widen an ordering surface.
/// </para>
/// <para>
/// <b>Comparison is case-insensitive and ordinal.</b> A query-string parameter is typed
/// by a human or generated by a client that may not match the projection's casing, so
/// <c>portalname</c>, <c>PortalName</c> and <c>PORTALNAME</c> all name the same field.
/// Ordinal rather than culture-aware comparison is deliberate: these are programmatic
/// identifiers, not words, and a culture-sensitive comparison of identifiers is how the
/// Turkish dotless-i class of defect arises.
/// </para>
/// <para>
/// Every set is an immutable frozen-shape <see cref="IReadOnlySet{T}"/> initialised
/// once, so the sets are safe to read from any number of concurrent requests and cannot
/// be mutated by a consumer that receives one.
/// </para>
/// </remarks>
// MIGRATION: CALLER-CHOSEN ORDERING IS NET-NEW, AND THE ABSENCE OF A LEGACY AUTHORITY IS
// MEASURED RATHER THAN ASSUMED. No markup under Website/admin declares a sorting
// affordance of any kind - the legacy grids rendered whatever order the stored procedure
// produced and offered the user no way to change it - which is also what
// Dtos/Common/PagedRequest.cs records on its own SortBy member. There is therefore no
// legacy set of sortable columns to transcribe, and inventing one from the legacy grid
// columns would be inventing policy while appearing to preserve it.
//
// MIGRATION: the sets below are derived from a stated rule instead: A FIELD IS SORTABLE
// WHEN IT IS PROJECTED BY THE COLLECTION'S LIST ITEM AND IS BACKED BY A COLUMN THE
// LISTING QUERY ALREADY READS. Both halves matter. The first half means a caller can only
// order by something the response actually shows, so an ordering is always explicable from
// the payload in front of the user. The second half means the repository can honour the
// request with the tables it already joins, so a name that is accepted at the boundary
// cannot fail deeper down - which is the failure mode an allowlist exists to prevent.
// Every member excluded by that rule is named below with the reason, so a later reader can
// see that the exclusion was a decision rather than an oversight.
internal static class SortableFields
{
    /// <summary>
    /// Field names that may order the portal listing served by
    /// <c>GET /api/v1/portals</c>.
    /// </summary>
    /// <remarks>
    /// Projected by <c>PortalListItemDto</c> and backed by columns on <c>Portals</c>:
    /// <c>PortalID</c> (<c>01.00.00.SqlDataProvider:L77</c>), <c>PortalName</c>
    /// (<c>:L79</c>), <c>ExpiryDate</c> (<c>:L83</c>), <c>HostFee</c> - terminal type
    /// <c>money NOT NULL</c> after <c>03.01.01.SqlDataProvider:L1118</c> - and
    /// <c>HostSpace</c> (<c>int NOT NULL</c> after <c>:L1119</c>).
    /// </remarks>
    // MIGRATION: three members of the projection are deliberately absent.
    //   - Users and Pages are COMPUTED COUNTS, not columns. PortalInfo.vb declares them at
    //     L309 and L320 and no Portals column of either name exists anywhere in the
    //     eighty-eight-script chain, so ordering by them would require the listing query
    //     to aggregate over two other tables first.
    //   - Aliases is a COLLECTION. A portal may hold several aliases, so there is no single
    //     value to order by; ordering by a collection has no defined meaning.
    internal static readonly IReadOnlySet<string> Portals =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "PortalId",
            "PortalName",
            "ExpiryDate",
            "HostFee",
            "HostSpace",
        };

    /// <summary>
    /// Field names that may order the role listing served by
    /// <c>GET /api/v1/portals/{portalId}/roles</c>.
    /// </summary>
    /// <remarks>
    /// Every member of <c>RoleListItemDto</c> is included, because every one is backed by
    /// a column on <c>Roles</c>: <c>RoleID</c> and <c>RoleName</c>
    /// (<c>01.00.00.SqlDataProvider:L114</c> onwards), <c>Description</c>,
    /// <c>ServiceFee</c> (<c>money NULL</c>, <c>03.01.01.SqlDataProvider:L1173</c>),
    /// <c>BillingFrequency</c> and <c>TrialFrequency</c> (<c>char(1) NULL</c>),
    /// <c>BillingPeriod</c> and <c>TrialPeriod</c> (<c>int NULL</c>), <c>TrialFee</c>,
    /// <c>IsPublic</c> and <c>AutoAssignment</c>
    /// (<c>01.00.08.SqlDataProvider:L6828</c>). Preserving the paid-membership fields is a
    /// functional-parity requirement, which is why they are orderable rather than merely
    /// displayable.
    /// </remarks>
    internal static readonly IReadOnlySet<string> Roles =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "RoleId",
            "RoleName",
            "Description",
            "ServiceFee",
            "BillingFrequency",
            "BillingPeriod",
            "TrialFee",
            "TrialFrequency",
            "TrialPeriod",
            "IsPublic",
            "AutoAssignment",
        };

    /// <summary>
    /// Field names that may order the account listing served by
    /// <c>GET /api/v1/portals/{portalId}/users</c>.
    /// </summary>
    /// <remarks>
    /// Backed either by a column on <c>Users</c> - <c>UserID</c>, <c>Username</c>,
    /// <c>FirstName</c>, <c>LastName</c>, <c>DisplayName</c>, <c>Email</c> - or by a
    /// column on <c>UserPortals</c>, which the portal-scoped listing must join in any
    /// case: <c>CreatedDate</c> and <c>LastLoginDate</c>
    /// (<c>01.00.02.SqlDataProvider:L254</c>) and <c>Authorized</c>
    /// (<c>01.00.00.SqlDataProvider:L153</c>), surfaced by the projection as
    /// <c>IsApproved</c>. <c>IsSuperUser</c> is a <c>Users</c> column
    /// (<c>01.00.02.SqlDataProvider:L242-L243</c>).
    /// </remarks>
    // MIGRATION: five members of the projection are deliberately absent, and each for a
    // structural reason rather than a stylistic one.
    //   - Address and Telephone are PROFILE VALUES, not account columns. They live as
    //     key-value rows in UserProfile (03.02.03.SqlDataProvider:L1364) keyed by property
    //     definition, so ordering by either would require pivoting a second table.
    //     IUserService records the same fact about the legacy grid: those two columns
    //     reached the screen through the profile projection rather than as account columns.
    //   - IsOnline is DERIVED from the users-online tracking whose purge job this migration
    //     omits; there is no column to order by.
    //   - IsLockedOut belongs to the EXTERNAL aspnet_* membership store, which this
    //     solution maps alongside rather than owns.
    //   - PortalId is CONSTANT within a portal-scoped listing, so ordering by it cannot
    //     change the order of any page.
    internal static readonly IReadOnlySet<string> Users =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "UserId",
            "Username",
            "FirstName",
            "LastName",
            "DisplayName",
            "Email",
            "CreatedDate",
            "LastLoginDate",
            "IsApproved",
            "IsSuperUser",
        };

    /// <summary>
    /// The union of every per-collection set: the outer bound that
    /// <c>PagedRequestValidator</c> applies to any request, whichever collection it
    /// addresses.
    /// </summary>
    /// <remarks>
    /// Built from the sets above rather than restated, so adding a field to a collection
    /// cannot leave the outer bound behind. A name in this set is guaranteed to be a
    /// constant declared in this file and therefore safe to compose into an ordering
    /// clause; whether it is meaningful for the collection actually being read is settled
    /// by the per-collection set.
    /// </remarks>
    internal static readonly IReadOnlySet<string> All = BuildUnion();

    /// <summary>
    /// Reports whether the supplied name is a member of the union.
    /// </summary>
    /// <param name="fieldName">
    /// The name a caller supplied, which may be <see langword="null"/>, empty or entirely
    /// white space.
    /// </param>
    /// <returns>
    /// <see langword="true"/> when <paramref name="fieldName"/> is absent - because an
    /// absent sort field expresses no preference and is not an error - or when it names a
    /// field in <see cref="All"/>; otherwise <see langword="false"/>.
    /// </returns>
    /// <remarks>
    /// Absence is reported as acceptable so that a caller who supplies no ordering is not
    /// forced to reason about the allowlist at all. The absent-versus-blank question is
    /// settled the same way <c>PagedRequest.HasSort</c> settles it, so the validator and
    /// the contract cannot disagree about what "no preference" means.
    /// </remarks>
    internal static bool IsPermitted(string? fieldName) =>
        string.IsNullOrWhiteSpace(fieldName) || All.Contains(fieldName);

    /// <summary>
    /// Combines the per-collection sets into the union exposed by <see cref="All"/>.
    /// </summary>
    /// <returns>An immutable, case-insensitive set holding every permitted field name.</returns>
    private static IReadOnlySet<string> BuildUnion()
    {
        HashSet<string> union = new(StringComparer.OrdinalIgnoreCase);

        union.UnionWith(Portals);
        union.UnionWith(Roles);
        union.UnionWith(Users);

        return union;
    }
}
