namespace DnnMigration.Application.Validation;

/// <summary>
/// The closed sets of field names a caller may name in <c>PagedRequest.SortBy</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Closed by default.</b> A name that appears in no set below is rejected at the
/// boundary. The point of an allowlist rather than a pattern is that no caller-supplied
/// text ever reaches an <c>ORDER BY</c> clause: what reaches the repository is a member
/// of a set fixed at compile time, so the ordering clause is composed from constants
/// this assembly owns rather than from anything that arrived on the wire. A pattern
/// rule - "letters and digits only", say - would still hand the repository a string it
/// had to trust, and would have to be tightened again every time someone widened it.
/// </para>
/// <para>
/// <b>Two levels, and the per-collection level is the one that binds.</b> Each set below
/// is applied AT THE BOUNDARY by its own sealed validator over its own derived request
/// type - <c>PortalPagedRequestValidator</c> over <c>PortalPagedRequest</c>, and so on -
/// so naming a portal field while reading accounts is a field-level 400 rather than a
/// silently ignored parameter. That arrangement replaces an earlier one in which the union
/// was the only bound anything applied: FluentValidation resolves one validator per
/// request TYPE, every collection endpoint bound the one shared <c>PagedRequest</c>, and
/// the per-collection sets below consequently had no consumer at all. Deriving a request
/// type per collection is what gives the narrow sets somewhere to be enforced.
/// </para>
/// <para>
/// <see cref="All"/> remains as the union and is applied to a bare <c>PagedRequest</c> -
/// a shape no registered endpoint now binds, but one the contract still permits - so an
/// unrecognised name is refused even there. It is built from the sets rather than restated,
/// so a field added to a collection cannot leave the outer bound behind. Every set is
/// <see langword="internal"/> because the validators and listings that consult them live
/// in this same assembly; nothing outside it needs, or is given, the ability to widen an
/// ordering surface.
/// </para>
/// <para>
/// <b>Comparison is case-insensitive and ordinal.</b> A query-string parameter is typed
/// by a human or generated by a client that may not match the projection's casing, so
/// <c>portalname</c>, <c>PortalName</c> and <c>PORTALNAME</c> all name the same field.
/// Ordinal rather than culture-aware comparison is deliberate: these are programmatic
/// identifiers, not words, and a culture-sensitive comparison of identifiers is how the
/// Turkish dotless-i class of defect arises.
/// </para>
/// <para>
/// Every set is an immutable frozen-shape <see cref="IReadOnlySet{T}"/> initialised
/// once, so the sets are safe to read from any number of concurrent requests and cannot
/// be mutated by a consumer that receives one.
/// </para>
/// </remarks>
// MIGRATION: CALLER-CHOSEN ORDERING IS NET-NEW, AND THE ABSENCE OF A LEGACY AUTHORITY IS
// MEASURED RATHER THAN ASSUMED. No markup under Website/admin declares a sorting
// affordance of any kind - the legacy grids rendered whatever order the stored procedure
// produced and offered the user no way to change it - which is also what
// Dtos/Common/PagedRequest.cs records on its own SortBy member. There is therefore no
// legacy set of sortable columns to transcribe, and inventing one from the legacy grid
// columns would be inventing policy while appearing to preserve it.
//
// MIGRATION: the sets below are derived from a stated rule instead: A FIELD IS SORTABLE
// WHEN IT IS PROJECTED BY THE COLLECTION'S LIST ITEM, IS BACKED BY A COLUMN THE LISTING
// QUERY ALREADY READS, AND IS ACTUALLY HONOURED BY THAT LISTING. All three halves matter.
// The first means a caller can only order by something the response actually shows, so an
// ordering is always explicable from the payload in front of the user. The second means the
// listing can honour the request with the tables it already reads, so a name accepted at the
// boundary cannot fail deeper down. The third was added after review found the first two
// insufficient on their own: several names satisfied both and were nevertheless DISCARDED by
// the listing, which answered 200 with an order the caller had not asked for - a silent
// failure strictly worse than a rejection, because nothing in the response says the request
// was not carried out. Every listing now applies every name in its own set, and every member
// excluded is named below with the reason, so a later reader can see that an exclusion was a
// decision rather than an oversight.
internal static class SortableFields
{
    /// <summary>
    /// Field names that may order the portal listing served by
    /// <c>GET /api/v1/portals</c>.
    /// </summary>
    /// <remarks>
    /// Projected by <c>PortalListItemDto</c> and backed by columns on <c>Portals</c>:
    /// <c>PortalID</c> (<c>01.00.00.SqlDataProvider:L77</c>), <c>PortalName</c>
    /// (<c>:L79</c>), <c>ExpiryDate</c> (<c>:L83</c>), <c>HostFee</c> - terminal type
    /// <c>money NOT NULL</c> after <c>03.01.01.SqlDataProvider:L1118</c> - and
    /// <c>HostSpace</c> (<c>int NOT NULL</c> after <c>:L1119</c>).
    /// </remarks>
    // MIGRATION: three members of the projection are deliberately absent.
    //   - Users and Pages are COMPUTED COUNTS, not columns. PortalInfo.vb declares them at
    //     L309 and L320 and no Portals column of either name exists anywhere in the
    //     eighty-eight-script chain, so ordering by them would require the listing query
    //     to aggregate over two other tables first.
    //   - Aliases is a COLLECTION. A portal may hold several aliases, so there is no single
    //     value to order by; ordering by a collection has no defined meaning.
    //
    // Every one of the five IS honoured by PortalRepository.ApplyOrder. HostFee and HostSpace
    // were advertised here and fell through that method's default arm to PortalName, so a
    // caller who asked to order by hosting charge received an alphabetical page and no
    // indication that the request had been discarded. The two arms exist now. In the other
    // direction that method also honoured Description and Currency, neither of which this
    // set admits and neither of which PortalListItemDto projects, so both arms were
    // unreachable dead code and were removed rather than advertised.
    internal static readonly IReadOnlySet<string> Portals =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "PortalId",
            "PortalName",
            "ExpiryDate",
            "HostFee",
            "HostSpace",
        };

    /// <summary>
    /// Field names that may order the role listing served by
    /// <c>GET /api/v1/roles</c>.
    /// </summary>
    /// <remarks>
    /// Every member of <c>RoleListItemDto</c> is included, because every one is backed by
    /// a column on <c>Roles</c>: <c>RoleID</c> and <c>RoleName</c>
    /// (<c>01.00.00.SqlDataProvider:L114</c> onwards), <c>Description</c>,
    /// <c>ServiceFee</c> (<c>money NULL</c>, <c>03.01.01.SqlDataProvider:L1173</c>),
    /// <c>BillingFrequency</c> and <c>TrialFrequency</c> (<c>char(1) NULL</c>),
    /// <c>BillingPeriod</c> and <c>TrialPeriod</c> (<c>int NULL</c>), <c>TrialFee</c>,
    /// <c>IsPublic</c> and <c>AutoAssignment</c>
    /// (<c>01.00.08.SqlDataProvider:L6828</c>). Preserving the paid-membership fields is a
    /// functional-parity requirement, which is why they are orderable rather than merely
    /// displayable.
    /// </remarks>
    internal static readonly IReadOnlySet<string> Roles =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "RoleId",
            "RoleName",
            "Description",
            "ServiceFee",
            "BillingFrequency",
            "BillingPeriod",
            "TrialFee",
            "TrialFrequency",
            "TrialPeriod",
            "IsPublic",
            "AutoAssignment",
        };

    /// <summary>
    /// Field names that may order the account listing served by
    /// <c>GET /api/v1/users</c>.
    /// </summary>
    /// <remarks>
    /// Every member is a mapped column on <c>Users</c> that the listing query reads directly:
    /// <c>UserID</c>, <c>Username</c>, <c>FirstName</c>, <c>LastName</c>, <c>DisplayName</c>
    /// and <c>Email</c>, together with <c>IsSuperUser</c>
    /// (<c>01.00.02.SqlDataProvider:L242-L243</c>).
    /// </remarks>
    // MIGRATION: eight members of the projection are deliberately absent, and each for a
    // structural reason rather than a stylistic one.
    //   - Address and Telephone are PROFILE VALUES, not account columns. They live as
    //     key-value rows in UserProfile (03.02.03.SqlDataProvider:L1364) keyed by property
    //     definition, so ordering by either would require pivoting a second table.
    //     IUserService records the same fact about the legacy grid: those two columns
    //     reached the screen through the profile projection rather than as account columns.
    //   - IsOnline is DERIVED from the users-online tracking whose purge job this migration
    //     omits; there is no column to order by.
    //   - PortalId is CONSTANT within a portal-scoped listing, so ordering by it cannot
    //     change the order of any page.
    //   - CreatedDate, LastLoginDate, IsApproved and IsLockedOut ARE PROJECTED BUT ARE NOT
    //     PART OF THE QUERY, and this is the correction review found. UserConfiguration
    //     Ignore()s all four on the User entity - they are not mapped columns of the entity
    //     the listing pages over - and UserRepository fills them AFTER the page has been
    //     taken, from the external aspnet_* membership store and the UserPortals join, in
    //     PopulateAsync. Ordering by a value that does not exist until after Skip and Take
    //     have run would order the page rather than the collection, which is not an ordering
    //     at all: page two would be sorted among itself and would still hold whichever rows
    //     the underlying order put there. They were advertised and silently discarded, and
    //     they are withdrawn rather than faked. Honouring them properly means projecting the
    //     membership store into the query, which is a data-access change no finding asks for
    //     and which the AAP places outside this work - the aspnet_* objects are an external
    //     dependency this solution maps alongside rather than owns (AAP 0.7.1.3).
    internal static readonly IReadOnlySet<string> Users =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "UserId",
            "Username",
            "FirstName",
            "LastName",
            "DisplayName",
            "Email",
            "IsSuperUser",
        };

    /// <summary>
    /// Field names that may order the module listing served by
    /// <c>GET /api/v1/modules</c>.
    /// </summary>
    /// <remarks>
    /// This set is NET-NEW, and its absence was itself part of the defect: the module listing
    /// bound the shared request contract and was therefore bounded only by the union, so it
    /// accepted every portal and role field name and discarded all of them. Each member below
    /// is projected by <c>ModuleListItemDto</c> and is backed by a column the listing already
    /// materialises - <c>ModuleID</c>, <c>ModuleTitle</c> and <c>IsDeleted</c> on
    /// <c>Modules</c>, and <c>StartDate</c> and <c>EndDate</c> on the same table.
    /// </remarks>
    // MIGRATION: eight members of the projection are deliberately absent.
    //   - TabModuleId, TabId, ModuleOrder, AllTabs, Visibility and DisplayTitle belong to the
    //     PLACEMENT rather than to the module. A module may be placed on many pages, so each
    //     has as many values as the module has placements and there is no single value to
    //     order the module by. The projection shows the placement the listing selected, which
    //     is a display choice rather than an orderable fact.
    //   - ModuleDefId and FriendlyName come from the DEFINITION, which the listing resolves
    //     per row after the page has been taken; ordering by either would order the page
    //     rather than the collection.
    internal static readonly IReadOnlySet<string> Modules =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "ModuleId",
            "ModuleTitle",
            "IsDeleted",
            "StartDate",
            "EndDate",
        };

    /// <summary>
    /// Field names that may order the role-membership listing served by
    /// <c>GET /api/v1/roles/{roleId}/users</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Every name below is an ACCOUNT field, because the legacy grid rendered the account and sorted on
    /// what it rendered.
    /// </para>
    /// <para>
    /// ⚠ SEC-F11. THREE NAMES WERE WITHDRAWN FROM THIS SET, AND THE COMMENT THAT JUSTIFIED THEM WAS WRONG.
    /// <c>CreatedDate</c>, <c>LastLoginDate</c> and <c>IsApproved</c> were admitted on the reading that this
    /// listing materialises the role's assignments and pages them IN MEMORY, so the three values the
    /// external <c>aspnet_*</c> membership objects supply would be present on every row before a page was
    /// cut. The implementation does not do that: the filter, the ordering, the count and the window all
    /// travel to the store, and the repository's ordering arm for those three names fell through to the
    /// assignment key. A caller asking for them was answered <c>200</c> with rows ordered by something else
    /// entirely - and the membership projection does not carry the three values, so the response could not
    /// even be inspected to notice. An ordering the store cannot perform over a value the response does not
    /// publish is not a capability, so it is no longer advertised: the boundary now refuses those names with
    /// a field-keyed <c>400</c> naming <c>sortBy</c>.
    /// </para>
    /// <para>
    /// It is narrower than the projection: the two assignment dates the projection carries are deliberately
    /// not orderable, because the legacy grid offered no ordering by them, and the role identifier is fixed
    /// by the route for every record on the page, so ordering by it could not change any order.
    /// <c>IRoleService</c> records both reductions.
    /// </para>
    /// </remarks>
    internal static readonly IReadOnlySet<string> RoleUsers =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "UserId",
            "Username",
            "FirstName",
            "LastName",
            "DisplayName",
            "Email",
            "IsSuperUser",
        };

    /// <summary>
    /// The union of every per-collection set: the outer bound that
    /// <c>PagedRequestValidator</c> applies to any request, whichever collection it
    /// addresses.
    /// </summary>
    /// <remarks>
    /// Built from the sets above rather than restated, so adding a field to a collection
    /// cannot leave the outer bound behind. A name in this set is guaranteed to be a
    /// constant declared in this file and therefore safe to compose into an ordering
    /// clause; whether it is meaningful for the collection actually being read is settled
    /// by the per-collection set.
    /// </remarks>
    /// <summary>
    /// Field names that may order the account picker served by <c>GET /api/v1/users/choices</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// THE NARROWEST SET IN THIS FILE, AND NARROW FOR ONE REASON: it is exactly the projection. That
    /// endpoint returns a key and the two captions an option shows - <c>Users.Username</c> and
    /// <c>Users.DisplayName</c> - so those two are the only values a caller could see the effect of
    /// ordering by. Every other account field is absent from the payload by design, and ordering a
    /// drop-down by a value the operator cannot read is an ordering they cannot verify.
    /// </para>
    /// <para>
    /// The key itself is deliberately not a member. It orders the options by the accident of when each
    /// account was created, which is meaningless to somebody choosing one, and it is already the final
    /// tie-break on both arms so the sequence is total either way.
    /// </para>
    /// </remarks>
    internal static readonly IReadOnlySet<string> UserChoices =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "Username",
            "DisplayName",
        };

    internal static readonly IReadOnlySet<string> All = BuildUnion();

    /// <summary>
    /// Reports whether the supplied name is a member of the union.
    /// </summary>
    /// <param name="fieldName">
    /// The name a caller supplied, which may be <see langword="null"/>, empty or entirely
    /// white space.
    /// </param>
    /// <returns>
    /// <see langword="true"/> when <paramref name="fieldName"/> is absent - because an
    /// absent sort field expresses no preference and is not an error - or when it names a
    /// field in <see cref="All"/>; otherwise <see langword="false"/>.
    /// </returns>
    /// <remarks>
    /// Absence is reported as acceptable so that a caller who supplies no ordering is not
    /// forced to reason about the allowlist at all. The absent-versus-blank question is
    /// settled the same way <c>PagedRequest.HasSort</c> settles it, so the validator and
    /// the contract cannot disagree about what "no preference" means.
    /// </remarks>
    internal static bool IsPermitted(string? fieldName) =>
        string.IsNullOrWhiteSpace(fieldName) || All.Contains(fieldName);

    /// <summary>
    /// Reports whether the supplied name is a member of one particular collection's set.
    /// </summary>
    /// <param name="permitted">The collection's set, one of the members declared above.</param>
    /// <param name="fieldName">
    /// The name a caller supplied, which may be <see langword="null"/>, empty or entirely
    /// white space.
    /// </param>
    /// <returns>
    /// <see langword="true"/> when <paramref name="fieldName"/> is absent, or when it names a
    /// field in <paramref name="permitted"/>; otherwise <see langword="false"/>.
    /// </returns>
    /// <remarks>
    /// Absence is tolerated on exactly the same terms as in the union overload, so a caller who
    /// expressed no preference is never asked to justify a field they did not name. This overload
    /// is what the per-collection validators apply, and it is the reason the narrow sets are no
    /// longer declared without a consumer.
    /// </remarks>
    internal static bool IsPermitted(IReadOnlySet<string> permitted, string? fieldName)
    {
        ArgumentNullException.ThrowIfNull(permitted);

        return string.IsNullOrWhiteSpace(fieldName) || permitted.Contains(fieldName);
    }

    /// <summary>
    /// Reports whether the supplied name is a member of one specific collection's set.
    /// </summary>
    /// <param name="fieldName">
    /// The name a caller supplied, which may be <see langword="null"/>, empty or entirely
    /// white space.
    /// </param>
    /// <param name="permitted">The collection's set, one of the members declared above.</param>
    /// <returns>
    /// <see langword="true"/> when <paramref name="fieldName"/> is absent - an absent sort field
    /// expresses no preference and is never an error, whatever the collection - or when it is a
    /// member of <paramref name="permitted"/>; otherwise <see langword="false"/>.
    /// </returns>
    /// <remarks>
    /// This is the test each listing applies before it reads anything, and it is the narrower
    /// authority: <see cref="IsPermitted(string?)"/> only proves the name is a constant declared in
    /// this file, which is what keeps caller text out of an ordering clause, while this proves the
    /// name means something for the collection actually being read. It is the field-first spelling
    /// of <see cref="IsPermitted(IReadOnlySet{string}, string?)"/> and delegates to it, so the two
    /// call shapes used across the solution cannot answer differently.
    /// </remarks>
    internal static bool IsPermittedFor(string? fieldName, IReadOnlySet<string> permitted) =>
        IsPermitted(permitted, fieldName);

    /// <summary>
    /// Combines the per-collection sets into the union exposed by <see cref="All"/>.
    /// </summary>
    /// <returns>An immutable, case-insensitive set holding every permitted field name.</returns>
    private static IReadOnlySet<string> BuildUnion()
    {
        HashSet<string> union = new(StringComparer.OrdinalIgnoreCase);

        union.UnionWith(Portals);
        union.UnionWith(Roles);
        union.UnionWith(Users);
        union.UnionWith(UserChoices);
        union.UnionWith(Modules);
        union.UnionWith(RoleUsers);

        return union;
    }
}
