using DnnMigration.Domain.Common;

namespace DnnMigration.Domain.Entities;

/// <summary>
/// One module instance owned by a portal: the content unit that one or more pages display, and the
/// persistence shape of a single row of the legacy <c>dbo.Modules</c> table.
/// </summary>
/// <remarks>
/// The schema is immutable for this migration, so this file describes a table that already exists rather
/// than defining one. Three invariants govern every consumer.
/// </remarks>
public sealed class Module : Entity<int>
{
    /// <summary>
    /// Gets or sets the <c>ModuleID</c> column: <c>int IDENTITY(0, 1) NOT NULL</c>, the primary key,
    /// generated by the database.
    /// </summary>
    /// <remarks>
    /// Zero identifies the first module of a fresh installation and is therefore a real, persisted key.
    /// </remarks>
    // Dbo.Modules.ModuleID is declared IDENTITY(0, 1) - Website/Providers/
    // DataProviders/SqlDataProvider/01.00.00.SqlDataProvider line 221, recorded in the Modules.ModuleID
    // record of backend/tests/DnnMigration.IntegrationTests/Schema/TerminalSchema.manifest.
    public int ModuleId { get; set; }

    /// <inheritdoc />
    /// <remarks>
    /// Never mapped to a column. The entity configuration names <see cref="ModuleId"/> in its explicit key
    /// declaration; this member exists only so the base type can compare entities.
    /// </remarks>
    public override int Identity => ModuleId;

    /// <summary>
    /// Gets or sets the <c>ModuleDefID</c> column: <c>int NOT NULL</c>, the required foreign key to the
    /// definition this instance was created from.
    /// </summary>
    /// <remarks>
    /// Required in the schema since the table was created, with <c>FK_Modules_ModuleDefinitions ... ON
    /// DELETE CASCADE</c>, so removing a definition removes every instance of it.
    /// </remarks>
    // The column is spelled ModuleDefID, not ModuleDefinitionId. Infrastructure must therefore map this
    // property with HasColumnName("ModuleDefID"); relying on convention would look for a column that does
    // not exist.
    public int ModuleDefinitionId { get; set; }

    /// <summary>
    /// Gets or sets the <c>ModuleTitle</c> column: <c>nvarchar(256) NULL</c>, the title rendered in the
    /// module's container.
    /// </summary>
    /// <remarks>
    /// Nullable because the column is. An untitled module and a module titled with an empty string are
    /// distinct states here, which they were not in the legacy model.
    /// </remarks>
    public string? ModuleTitle { get; set; }

    /// <summary>
    /// Gets or sets the <c>AllTabs</c> column: <c>bit NOT NULL</c> defaulting to <c>0</c>, whether the
    /// instance appears on every page of its portal rather than only where it is placed.
    /// </summary>
    public bool AllTabs { get; set; }

    /// <summary>
    /// Gets or sets the <c>IsDeleted</c> column: <c>bit NOT NULL</c> defaulting to <c>0</c>, the
    /// soft-delete flag that moves the instance into the recycle bin without removing the row.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Gets or sets the <c>InheritViewPermissions</c> column: <c>bit NULL</c>, whether view access is
    /// inherited from the hosting page instead of being granted on the module itself.
    /// </summary>
    public bool? InheritViewPermissions { get; set; }

    /// <summary>
    /// Gets or sets the <c>Header</c> column: <c>ntext NULL</c>, raw markup emitted above the module's
    /// content.
    /// </summary>
    // 02.02.00 line 322 declares this `ntext NULL`. ntext is the terminal type and the schema is immutable,
    // so Infrastructure must preserve it rather than opportunistically converting the column to
    // nvarchar(max). No maximum length may be declared for it.
    public string? Header { get; set; }

    /// <summary>
    /// Gets or sets the <c>Footer</c> column: <c>ntext NULL</c>, raw markup emitted below the module's
    /// content.
    /// </summary>
    public string? Footer { get; set; }

    /// <summary>
    /// Gets or sets the <c>StartDate</c> column: <c>datetime NULL</c>, the instant from which the instance
    /// becomes visible.
    /// </summary>
    public DateTime? StartDate { get; set; }

    /// <summary>
    /// Gets or sets the <c>EndDate</c> column: <c>datetime NULL</c>, the instant after which the instance
    /// stops being visible.
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Gets or sets the <c>PortalID</c> column: <c>int NULL</c>, the optional foreign key to the portal
    /// that owns the instance.
    /// </summary>
    /// <remarks>
    /// Null is meaningful and expected: a module with no portal is owned by the installation itself. Zero
    /// and -1 are both real portal keys, because <c>dbo.Portals.PortalID</c> is <c>IDENTITY(-1, 1)</c>, so
    /// neither may be read as an absence.
    /// </remarks>
    // 03.00.01 line 12 adds this column as `PortalID int NULL` and the foreign key added at lines 208-215
    // declares no ON DELETE clause, so it stays nullable to the end of the chain.
    public int? PortalId { get; set; }

    /// <summary>Gets or sets the definition this instance was created from.</summary>
    /// <remarks>
    /// Required rather than optional, because <c>ModuleDefID</c> is <c>NOT NULL</c>: every module has a
    /// definition. It is nonetheless left <see langword="null"/> by any query that does not load it, which
    /// is why reading it defensively is still correct.
    /// </remarks>
    public ModuleDefinition ModuleDefinition { get; set; }

    /// <summary>
    /// Gets or sets the portal that owns the instance, or <see langword="null"/> for a module the
    /// installation owns.
    /// </summary>
    public Portal? Portal { get; set; }

    /// <summary>Gets the settings recorded against the instance itself, from <c>dbo.ModuleSettings</c>.</summary>
    /// <remarks>
    /// Replaces the untyped <c>Hashtable</c> the legacy model exposed. Settings scoped to a single
    /// placement are a different store and hang off <see cref="TabModule"/> instead.
    /// </remarks>
    public ICollection<ModuleSetting> Settings { get; } = new List<ModuleSetting>();

    /// <summary>Gets the placements of this instance on pages, from <c>dbo.TabModules</c>.</summary>
    /// <remarks>
    /// A unique index over <c>(TabID, ModuleID)</c> means the instance appears at most once on any given
    /// page, but it may appear on many.
    /// </remarks>
    public ICollection<TabModule> TabModules { get; } = new List<TabModule>();

    /// <summary>Gets the permission grants attached to this instance, from <c>dbo.ModulePermission</c>.</summary>
    public ICollection<ModulePermission> ModulePermissions { get; } = new List<ModulePermission>();
}
