using DnnMigration.Domain.Common;

namespace DnnMigration.Domain.Entities;

// Member names are idiomatic C#; column names are not renamed. The Infrastructure entity configuration must
// bind PortalAliasId to the column PortalAliasID, and HttpAlias to the column HTTPAlias in that exact
// upper-case spelling.

// That column was widened by the split which created this table, not narrowed.

// Two constraints the Infrastructure configuration must declare, because the schema already has them and
// Rule T4 forbids changing it.

// Resolving a request's host name to a tenant is deliberately NOT a member of this type. The lookup belongs
// to PortalAliasResolutionMiddleware and the alias repository, and it matches the stored value exactly.

/// <summary>One host name a portal answers on, modelling the terminal <c>dbo.PortalAlias</c> base table.</summary>
/// <remarks>
/// <para>
/// Every member is a persisted column of that table, in the table's own column order, plus the single
/// navigation to the owning portal.
/// </para>
/// <para>
/// Two invariants govern consumers. <see cref="HttpAlias"/> may be null, because the column permits null,
/// so code that requires a host name tests for one instead of assuming it.
/// </para>
/// </remarks>
public sealed class PortalAlias : Entity<int>
{
    /// <summary>The value equality is based on, which is always <see cref="PortalAliasId"/>.</summary>
    /// <remarks>
    /// Never mapped to a column; the entity configuration names <see cref="PortalAliasId"/> in its key
    /// declaration.
    /// </remarks>
    public override int Identity => PortalAliasId;

    /// <summary>
    /// The <c>PortalAliasID</c> column: <c>int IDENTITY(1, 1) NOT NULL</c>, the primary key
    /// <c>PK_PortalAlias</c>, generated by the database.
    /// </summary>
    /// <remarks>
    /// The column name must be stated explicitly by the entity configuration, because the member spells the
    /// acronym <c>Id</c> while the column spells it <c>ID</c>.
    /// </remarks>
    public int PortalAliasId { get; set; }

    /// <summary>
    /// The <c>PortalID</c> column: <c>int NOT NULL</c>, the foreign key to <c>dbo.Portals</c> under
    /// <c>FK_PortalAlias_Portals</c>, which the schema declares <c>ON DELETE CASCADE</c>.
    /// </summary>
    public int PortalId { get; set; }

    /// <summary>
    /// The <c>HTTPAlias</c> column: <c>nvarchar(200)</c>, nullable, carrying the installation-wide unique
    /// constraint <c>IX_PortalAlias</c>. Holds the host name a request may arrive on, optionally with a
    /// port and a virtual path - for example <c>www.example.com</c>, <c>localhost:8080</c> or
    /// <c>www.example.com/child</c>.
    /// </summary>
    /// <remarks>
    /// Nullable because the measured column declares no <c>NOT NULL</c>, and stored exactly as written:
    /// nothing here trims, lower-cases, strips a port, or substitutes an empty string for null.
    /// Case-insensitive comparison belongs to the repository, and normalising a submitted value belongs to
    /// the Application layer, so that the stored value stays the one the schema holds.
    /// </remarks>
    public string? HttpAlias { get; set; }

    /// <summary>
    /// The portal this alias resolves to: the principal end of <c>FK_PortalAlias_Portals</c>, paired with
    /// <see cref="Portal.PortalAliases"/>.
    /// </summary>
    /// <remarks>
    /// Non-nullable because the foreign key is: every row references a portal. Whether it is loaded remains
    /// the reader's choice, as with any reference navigation - a query that does not include it leaves it
    /// unset - so a caller either asks for the portal explicitly or works from <see cref="PortalId"/>.
    /// </remarks>
    public Portal Portal { get; set; }
}
