using DnnMigration.Domain.Common;

namespace DnnMigration.Domain.Entities;

/// <summary>
/// A page within a portal's navigation hierarchy: the DotNetNuke "tab" abstraction that module placements
/// and page-level permissions are keyed by.
/// </summary>
/// <remarks>
/// <para>
/// Obligations this type places on the Infrastructure layer, which owns mapping under Rules T3 and T4 and
/// may not alter the schema:
/// </para>
/// <para>
/// There is no unique constraint over the tenant and the page name at the terminal state: <c>IX_Tabs</c>
/// was added at <c>01.00.08.SqlDataProvider</c> line 6072 and dropped again at
/// <c>02.00.01.SqlDataProvider</c> line 64. Duplicate page names are therefore legal at the storage layer,
/// and rejecting them is an Application-layer rule rather than an invariant of this type.
/// </para>
/// </remarks>
public sealed class Tab : Entity<int>
{
    /// <summary>The value equality is based on, which is always <see cref="TabId"/>.</summary>
    /// <remarks>
    /// Never mapped to a column; the entity configuration names <see cref="TabId"/> in its <c>HasKey</c>
    /// call instead.
    /// </remarks>
    public override int Identity => TabId;

    /// <summary>
    /// The <c>TabID</c> column: <c>int IDENTITY(0, 1) NOT NULL</c>, the primary key <c>PK_Tabs</c>,
    /// generated by the database.
    /// </summary>
    /// <remarks>
    /// Zero keys a real page, because the identity seed is zero. No comparison against zero - and no
    /// comparison against any other reserved value - may be read as absence, and nothing may infer from
    /// this value whether the row has been written.
    /// </remarks>
    public int TabId { get; set; }

    /// <summary>
    /// The <c>TabOrder</c> column: <c>int NOT NULL</c> defaulting to <c>0</c>, the sort position among
    /// siblings sharing this page's parent.
    /// </summary>
    /// <remarks>
    /// Made <c>NOT NULL</c> with its default reasserted at <c>03.01.01.SqlDataProvider</c> lines 1278 and
    /// 1284. The legacy write path renumbered whole sibling sets, so values are not guaranteed contiguous
    /// and ordering must be by comparison, never by index.
    /// </remarks>
    public int TabOrder { get; set; }

    /// <summary>
    /// The <c>PortalID</c> column: <c>int NULL</c>, the owning tenant, or <see langword="null"/> for a host
    /// page that belongs to the installation rather than to any portal.
    /// </summary>
    public int? PortalId { get; set; }

    /// <summary>The <c>TabName</c> column: <c>nvarchar(50) NOT NULL</c>, the name shown in navigation.</summary>
    /// <remarks>
    /// Non-nullable because the column is, and carrying no initialiser on purpose. The legacy
    /// representation of "no text" was the empty string rather than <see langword="null"/>, so seeding this
    /// member with <see cref="string.Empty"/> would plant that sentinel in the domain and make an
    /// unsupplied name indistinguishable from a name of zero length.
    /// </remarks>
    public string TabName { get; set; }

    /// <summary>
    /// The <c>IsVisible</c> column: <c>bit NOT NULL</c> defaulting to <c>1</c>, whether the page appears in
    /// navigation.
    /// </summary>
    /// <remarks>
    /// The initialiser reproduces the store default declared as <c>DF_Tabs_IsVisible DEFAULT (1)</c> at
    /// <c>01.00.00.SqlDataProvider</c> line 497 and reasserted at <c>03.01.01.SqlDataProvider</c> line
    /// 1286, and is deliberate rather than incidental. It is not one of the banned legacy sentinels:
    /// <c>true</c> encodes a real value and never absence, and this column is not nullable.
    /// </remarks>
    public bool IsVisible { get; set; } = true;

    /// <summary>
    /// The <c>ParentId</c> column: <c>int NULL</c>, the page directly above this one, or <see
    /// langword="null"/> when this page sits at the root of its portal's hierarchy.
    /// </summary>
    /// <remarks>
    /// The self-reference added with <c>FK_Tabs_Tabs</c> at <c>01.00.04.SqlDataProvider</c> lines 46-50.
    /// Nullable because the column is; as with <see cref="PortalId"/> the legacy sentinel -1 stood for "no
    /// parent", and null must never be collapsed back to it.
    /// </remarks>
    public int? ParentId { get; set; }

    /// <summary>
    /// The <c>Level</c> column: <c>int NOT NULL</c> defaulting to <c>0</c>, the depth of this page in its
    /// hierarchy, zero at the root.
    /// </summary>
    /// <remarks>
    /// A denormalised count of the parent chain, maintained by the write path rather than derived on read,
    /// and preserved as stored. The identifier is keyword-adjacent and the schema brackets it as
    /// <c>[Level]</c>; quoting is the mapping layer's concern.
    /// </remarks>
    public int Level { get; set; }

    /// <summary>
    /// The <c>IconFile</c> column: <c>nvarchar(100) NULL</c>, the navigation icon, held exactly as stored.
    /// </summary>
    /// <remarks>
    /// This member carries the RAW base-table value, which for rows written through the file manager is the
    /// token <c>fileid=N</c> rather than a path.
    /// </remarks>
    public string? IconFile { get; set; }

    /// <summary>
    /// The <c>DisableLink</c> column: <c>bit NOT NULL</c> defaulting to <c>0</c>, whether the navigation
    /// entry is inert - rendered, but not a link.
    /// </summary>
    /// <remarks>
    /// Added at <c>01.00.10.SqlDataProvider</c> line 277 and made <c>NOT NULL</c> with its default
    /// reasserted at <c>03.01.01.SqlDataProvider</c> lines 1281 and 1290. Used for a heading that groups
    /// child pages without being navigable itself.
    /// </remarks>
    public bool DisableLink { get; set; }

    /// <summary>
    /// The <c>Title</c> column: <c>nvarchar(200) NULL</c>, the browser and search-result title, which the
    /// legacy screens allowed to differ from <see cref="TabName"/>.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// The <c>Description</c> column: <c>nvarchar(500) NULL</c>, the page description published as
    /// metadata.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// The <c>KeyWords</c> column: <c>nvarchar(500) NULL</c>, comma-separated search keywords published as
    /// metadata.
    /// </summary>
    /// <remarks>
    /// The member is spelled <c>Keywords</c> while the column it binds to is spelled <c>KeyWords</c>, with
    /// a capital W, as added at <c>02.00.00.SqlDataProvider</c> line 4754. The single word is the idiomatic
    /// C# form and matches the caption the legacy administration screens showed, and the column name is
    /// fixed by the shipped schema.
    /// </remarks>
    public string? Keywords { get; set; }

    /// <summary>
    /// The <c>IsDeleted</c> column: <c>bit NOT NULL</c> defaulting to <c>0</c>, the soft-delete flag that
    /// moves a page into the recycle bin.
    /// </summary>
    /// <remarks>
    /// A deletion sets this flag rather than removing the row, so read paths that present live pages must
    /// filter on it. Added at <c>02.00.00.SqlDataProvider</c> line 4755 and made <c>NOT NULL</c> with its
    /// default reasserted at <c>03.01.01.SqlDataProvider</c> lines 1282 and 1292.
    /// </remarks>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// The <c>Url</c> column: <c>nvarchar(255) NULL</c>, the alternative target of a page that redirects
    /// instead of hosting modules.
    /// </summary>
    /// <remarks>
    /// Added at <c>02.02.00.SqlDataProvider</c> line 40; the terminal view aliases the same column as
    /// <c>URL</c> at <c>04.05.04.SqlDataProvider</c> line 82, which is the identical column under a
    /// case-insensitive identifier.
    /// </remarks>
    public string? Url { get; set; }

    /// <summary>
    /// The <c>SkinSrc</c> column: <c>nvarchar(200) NULL</c>, the skin applied to this page, or <see
    /// langword="null"/> to inherit the portal's.
    /// </summary>
    public string? SkinSrc { get; set; }

    /// <summary>
    /// The <c>ContainerSrc</c> column: <c>nvarchar(200) NULL</c>, the default container skin for modules
    /// placed on this page, or <see langword="null"/> to inherit the portal's.
    /// </summary>
    public string? ContainerSrc { get; set; }

    /// <summary>
    /// The <c>TabPath</c> column: <c>nvarchar(255) NULL</c>, the materialised hierarchy path, for example
    /// <c>//Home//Reports</c>.
    /// </summary>
    /// <remarks>
    /// Added at <c>02.02.02.SqlDataProvider</c> line 3185. A denormalised copy of the parent chain that the
    /// legacy write path rebuilt whenever a page was moved or renamed; preserved as stored rather than
    /// recomputed, so it is authoritative only as far as the last write that maintained it.
    /// </remarks>
    public string? TabPath { get; set; }

    /// <summary>
    /// The <c>StartDate</c> column: <c>datetime NULL</c>, the instant from which the page is published, or
    /// <see langword="null"/> when it is published immediately.
    /// </summary>
    /// <remarks>
    /// Added at <c>02.02.02.SqlDataProvider</c> line 3186. Nullable because the column is: the legacy
    /// property was a non-nullable <c>Date</c> holding <c>Null.NullDate</c>, so <c>Date.MinValue</c> stood
    /// for "no start".
    /// </remarks>
    public DateTime? StartDate { get; set; }

    /// <summary>
    /// The <c>EndDate</c> column: <c>datetime NULL</c>, the instant after which the page stops being
    /// published, or <see langword="null"/> when it never expires.
    /// </summary>
    /// <remarks>
    /// Added at <c>02.02.02.SqlDataProvider</c> line 3187, and nullable for the same reason as <see
    /// cref="StartDate"/>. The two are not constrained relative to each other by the schema, so ordering
    /// them is an Application-layer validation rule.
    /// </remarks>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// The <c>RefreshInterval</c> column: <c>int NULL</c>, the client refresh period in seconds, or <see
    /// langword="null"/> when the page does not refresh itself.
    /// </summary>
    public int? RefreshInterval { get; set; }

    /// <summary>
    /// The <c>PageHeadText</c> column: <c>nvarchar(500) NULL</c>, additional markup injected into the
    /// rendered page head.
    /// </summary>
    /// <remarks>
    /// Added at <c>03.01.01.SqlDataProvider</c> line 410. Stored verbatim, which makes it caller-supplied
    /// markup: anything that renders it is responsible for its own escaping policy.
    /// </remarks>
    public string? PageHeadText { get; set; }

    /// <summary>
    /// The <c>IsSecure</c> column: <c>bit NOT NULL</c> defaulting to <c>0</c>, whether the page must be
    /// served over a secure transport.
    /// </summary>
    /// <remarks>
    /// This column exists only in the terminal schema, added last in the chain as <c>IsSecure bit NOT NULL
    /// CONSTRAINT DF_Tabs_IsSecure DEFAULT (0)</c> at <c>04.05.04.SqlDataProvider</c> lines 45-46, and the
    /// terminal <c>vw_Tabs</c> selects it at line 86. It must be mapped even though every earlier table
    /// definition lacks it, because the terminal state is the only authoritative one.
    /// </remarks>
    public bool IsSecure { get; set; }

    /// <summary>
    /// The owning tenant, the inverse of <see cref="Portal.Tabs"/>, or <see langword="null"/> for a host
    /// page and for any page loaded without this reference.
    /// </summary>
    public Portal? Portal { get; set; }

    /// <summary>
    /// The page directly above this one, the inverse of <see cref="Children"/>, or <see langword="null"/>
    /// at the root of the hierarchy and for any page loaded without this reference.
    /// </summary>
    /// <remarks>
    /// The <c>FK_Tabs_Tabs</c> end from <c>01.00.04.SqlDataProvider</c> lines 46-50. The constraint carries
    /// no <c>ON DELETE</c> clause, so the mapping must not introduce one: SQL Server rejects a cascade on a
    /// self-reference, and silently reparenting or deleting descendants behind the service layer is exactly
    /// the behaviour the shipped schema declines.
    /// </remarks>
    public Tab? Parent { get; set; }

    /// <summary>The pages that name this one as their parent, the inverse of <see cref="Parent"/>.</summary>
    /// <remarks>
    /// Empty rather than null on a newly constructed page, and empty on a page loaded without its children
    /// - the two are indistinguishable here, so emptiness alone does not establish that a page is a leaf.
    /// </remarks>
    public ICollection<Tab> Children { get; } = new List<Tab>();

    /// <summary>
    /// The module placements on this page, each carrying the presentation that varies per placement.
    /// </summary>
    public ICollection<TabModule> TabModules { get; } = new List<TabModule>();

    /// <summary>The permission grants and denials attached to this page.</summary>
    /// <remarks>
    /// The inverse of <see cref="TabPermission.Tab"/>, and the sole expression of page authority since
    /// <c>03.00.01.SqlDataProvider</c> lines 1407-1411 dropped the delimited <c>AuthorizedRoles</c> and
    /// <c>AdministratorRoles</c> columns in favour of rows. Evaluating these grants belongs to the
    /// Infrastructure permission evaluator, not to this type.
    /// </remarks>
    public ICollection<TabPermission> TabPermissions { get; } = new List<TabPermission>();
}
